"""Builds the full tableformoreapp.com static site: index.html, about.html,
privacy.html, terms.html, support.html — one shared design system, Deep Jade
/ Warm Ivory, Bricolage Grotesque (display) + IBM Plex Sans (body, clean and
neutral — no serif). Also writes icon.png, og-image.png, favicon.png,
hero-app.png (a real app screenshot, static, not regenerated by this script),
robots.txt, sitemap.xml as real files (not inlined) for fast loads and so
social/search crawlers can actually fetch them.

Run from the site repo directory: python3 build-site.py
"""
import re
import shutil
from pathlib import Path

SITE_URL = "https://tableformoreapp.com"
ASSETS = Path("/Users/lily/Project TABLEFORMORE/assets/images")

for name in ("icon.png", "favicon.png"):
    shutil.copy(ASSETS / name, Path(name))
ICON = "/icon.png"
OG_IMAGE = f"{SITE_URL}/og-image.png"

CSS = """
  :root {
    --bg: #FFFCF7; --surface: #FFFFFF; --surface-2: #FBF6EC; --border: #E7E9E5;
    --ink: #202421; --ink-soft: #5B615C; --ink-mute: #8B9089;
    --jade: #167D6A; --jade-dark: #106456; --jade-tint: #DDF3EC;
    --gold: #D69A1E; --coral: #C9765A;
    --danger: #C23B22; --danger-soft: #F8DFD8;
    --shadow: 0 20px 50px -25px rgba(16, 100, 86, 0.35);
    --font-display: 'Bricolage Grotesque', 'Avenir Next', 'Segoe UI', system-ui, sans-serif;
    --font-tagline: 'Manrope', 'Avenir Next', 'Segoe UI', system-ui, sans-serif;
    --font-body: 'IBM Plex Sans', 'Helvetica Neue', Arial, system-ui, sans-serif;
  }
  /* Deliberately one committed palette, no dark-mode variant — the brand is
     Warm Ivory / Deep Jade specifically, and it should look the same
     whether the visitor's phone is in light or dark mode. */
  html { color-scheme: light; }
  * { box-sizing: border-box; }
  img { max-width: 100%; height: auto; }
  html { scroll-behavior: smooth; }
  body { margin: 0; background: var(--bg); color: var(--ink); font-family: var(--font-body); font-size: 16px; line-height: 1.6; }
  a { color: var(--jade); }
  strong { font-weight: 600; }
  ::selection { background: var(--jade-tint); color: var(--jade-dark); }

  header.top { border-bottom: 1px solid var(--border); position: sticky; top: 0; background: color-mix(in srgb, var(--bg) 88%, transparent); backdrop-filter: blur(10px); z-index: 10; }
  .top-inner { max-width: 1080px; margin: 0 auto; padding: 16px 24px; display: flex; flex-wrap: wrap; row-gap: 10px; align-items: center; gap: 12px; }
  .brand { display: flex; align-items: center; gap: 9px; text-decoration: none; color: var(--ink); }
  .mark { width: 30px; height: 30px; border-radius: 22.37%; flex: none; display: block; }
  .wordmark { font-family: var(--font-display); font-weight: 700; font-size: 15px; letter-spacing: -0.01em; }
  nav.crosslinks { margin-left: auto; display: flex; align-items: center; gap: 20px; }
  nav.crosslinks a { font-family: var(--font-display); font-size: 13px; font-weight: 600; color: var(--ink-soft); text-decoration: none; }
  nav.crosslinks a:hover, nav.crosslinks a:focus-visible { color: var(--jade); }
  nav.crosslinks a[aria-current="page"] { color: var(--jade); }
  .nav-cta { background: var(--jade); color: var(--bg) !important; padding: 8px 16px; border-radius: 999px; }
  .nav-cta:hover { background: var(--jade-dark); }
  /* On a phone, keep the navigation on its own balanced row. A fixed gap
     makes the three differently sized labels bunch together; distributing
     them across a capped width gives About, Support and Coming soon equal
     visual breathing room without letting them hug the screen edges. */
  @media (max-width: 600px) {
    nav.crosslinks { width: min(100%, 340px); margin: 0 auto; justify-content: space-between; gap: 0; }
  }

  /* Doc pages (About/Support/Privacy/Terms): a wide two-column frame so the
     page uses the viewport instead of floating a narrow column in empty
     space — content on the left, a sticky rail (TOC or a contact card) on
     the right. Collapses to one column on narrower screens. */
  .doc-frame { max-width: 1120px; margin: 0 auto; padding: 44px 24px 64px; display: grid; grid-template-columns: minmax(0, 700px) 240px; gap: 64px; align-items: start; justify-content: start; }
  @media (max-width: 900px) { .doc-frame { grid-template-columns: minmax(0, 700px); } .doc-rail { display: none; } }
  main { min-width: 0; }
  .doc-rail { position: sticky; top: 84px; display: flex; flex-direction: column; gap: 20px; }
  .rail-card { background: var(--surface); border: 1px solid var(--border); border-radius: 16px; padding: 20px; }
  .rail-card .rail-title { font-family: var(--font-display); font-size: 11.5px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; color: var(--ink-mute); margin: 0 0 12px; }
  .toc { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 2px; }
  .toc a { display: block; font-family: var(--font-display); font-size: 13px; font-weight: 500; color: var(--ink-soft); text-decoration: none; padding: 6px 0; border-left: 2px solid transparent; padding-left: 12px; margin-left: -13px; }
  .toc a:hover { color: var(--jade); }
  .rail-card p { font-size: 13.5px; color: var(--ink-soft); margin: 0 0 12px; }
  .rail-card a.email { font-family: var(--font-display); font-weight: 700; font-size: 14px; color: var(--jade); text-decoration: none; overflow-wrap: anywhere; }
  .eyebrow { font-family: var(--font-display); font-size: 11.5px; font-weight: 700; letter-spacing: 0.09em; text-transform: uppercase; color: var(--jade); margin: 0 0 10px; }
  /* line-height was 1.12 — genuinely too tight for an 800-weight display
     face at this size: real bug, not a styling nit. Bricolage Grotesque's
     ascenders (f, t, l, b, h, k, capitals) were getting their tops clipped
     by the line box, worst on "food" and "Four steps" specifically since
     both start a line with a tall ascender right after the cap-height. */
  h1 { font-family: var(--font-display); font-weight: 800; font-size: clamp(28px, 5vw, 38px); line-height: 1.25; margin: 0 0 14px; text-wrap: balance; letter-spacing: -0.015em; overflow-wrap: anywhere; }
  .meta { display: flex; flex-wrap: wrap; gap: 6px 16px; font-family: var(--font-display); font-size: 12.5px; color: var(--ink-mute); margin-bottom: 32px; }
  .lede { font-size: 17px; color: var(--ink-soft); margin: 0 0 8px; }
  h2 { font-family: var(--font-display); font-weight: 700; font-size: 20px; line-height: 1.25; color: var(--jade); letter-spacing: -0.005em; margin: 36px 0 12px; overflow-wrap: anywhere; }
  h3 { font-family: var(--font-display); font-weight: 700; font-size: 16px; margin: 24px 0 8px; }
  p { margin: 0 0 15px; max-width: 66ch; }
  ul, ol { margin: 0 0 15px; padding-left: 20px; }
  li { margin-bottom: 7px; max-width: 62ch; }
  .callout { background: var(--jade-tint); border: 1px solid var(--jade); border-radius: 14px; padding: 15px 18px; margin: 22px 0; font-family: var(--font-display); font-size: 13.5px; color: var(--ink); }
  .callout.warn { background: var(--danger-soft); border-color: var(--danger); }
  .callout p:last-child { margin-bottom: 0; }
  /* FAQ accordion: collapsed by default (native <details>, no JS) so the
     page reads as a scannable list of questions at rest, not eleven fully
     expanded paragraphs stacked on top of each other. */
  .faq-group { margin-bottom: 8px; }
  .faq-group-title { font-family: var(--font-display); font-size: 12px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; color: var(--ink-mute); margin: 36px 0 4px; }
  .faq-group-title:first-child { margin-top: 4px; }
  details.faq-item { border-bottom: 1px solid var(--border); padding: 4px 0; }
  details.faq-item summary { list-style: none; cursor: pointer; padding: 14px 28px 14px 0; position: relative; font-family: var(--font-display); font-weight: 600; font-size: 15px; }
  details.faq-item summary::-webkit-details-marker { display: none; }
  details.faq-item summary::after { content: "+"; position: absolute; right: 2px; top: 12px; font-size: 20px; font-weight: 400; color: var(--ink-mute); line-height: 1; }
  details.faq-item[open] summary::after { content: "\\2212"; }
  details.faq-item[open] summary { color: var(--jade); }
  details.faq-item p { margin: 0 0 16px; font-size: 14.5px; color: var(--ink-soft); padding-right: 28px; }
  table { width: 100%; border-collapse: collapse; margin: 0 0 20px; font-family: var(--font-display); font-size: 13.5px; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid var(--border); vertical-align: top; }
  th { color: var(--ink-mute); font-weight: 600; font-size: 11.5px; text-transform: uppercase; letter-spacing: 0.04em; }
  .tablewrap { overflow-x: auto; border: 1px solid var(--border); border-radius: 12px; margin: 0 0 24px; }
  .tablewrap table { margin: 0; }
  .tablewrap th:first-child, .tablewrap td:first-child { padding-left: 16px; }

  footer.site { border-top: 1px solid var(--border); margin-top: 40px; }
  .footer-inner { max-width: 1080px; margin: 0 auto; padding: 32px 24px 44px; display: flex; flex-wrap: wrap; gap: 16px 32px; align-items: center; font-family: var(--font-display); font-size: 12.5px; color: var(--ink-mute); }
  .footer-inner nav { display: flex; gap: 16px; margin-left: auto; flex-wrap: wrap; }
  .footer-inner a { color: var(--ink-soft); text-decoration: none; }
  .footer-inner a:hover { color: var(--jade); }

  /* ---- marketing homepage ---- */
  .hero { max-width: 1080px; margin: 0 auto; padding: 56px 24px 36px; display: grid; grid-template-columns: minmax(0, 1.1fr) minmax(0, 0.9fr); gap: 44px; align-items: center; }
  @media (max-width: 860px) { .hero { grid-template-columns: 1fr; padding-top: 36px; gap: 20px; } }
  /* Below 860px the art drops under the text instead of beside it — capped
     small here so it reads as a supporting flourish under the headline,
     not an equal second hero. */
  @media (max-width: 860px) { .hero-art { max-width: 220px; margin: 0 auto; } }
  .hero h1 { font-size: clamp(32px, 5vw, 50px); }
  .hero h1.hero-tagline { font-family: var(--font-tagline); font-weight: 700; letter-spacing: -0.035em; }
  .hero-emoji { font-size: 26px; letter-spacing: 0.08em; margin-bottom: 16px; }
  .hero-sub { font-size: 17.5px; color: var(--ink-soft); max-width: 42ch; margin-bottom: 26px; }
  .hero-note { max-width: 42ch; margin: -12px 0 24px; padding-left: 12px; border-left: 3px solid var(--jade); color: var(--ink-soft); font-size: 14px; line-height: 1.5; }
  .badges { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 16px; }
  .badge { font-family: var(--font-display); font-weight: 600; font-size: 13.5px; border: 1.5px solid var(--border); border-radius: 12px; padding: 11px 16px; display: flex; flex-direction: column; gap: 2px; color: var(--ink); text-decoration: none; background: var(--surface); transition: border-color .15s, transform .15s; }
  .badge:hover { border-color: var(--jade); transform: translateY(-1px); }
  .badge span.small { font-size: 10.5px; font-weight: 500; color: var(--ink-mute); text-transform: uppercase; letter-spacing: 0.05em; }
  .badge span.big { font-size: 14px; }
  .soon-note { font-family: var(--font-display); font-size: 12.5px; color: var(--ink-mute); }

  .hero-art { position: relative; display: grid; place-items: center; }

  /* Real product screenshot in a phone frame, not an invented icon — after
     several abstract-symbol rounds, showing the actual app directly. */
  .phone-frame { position: relative; width: 100%; max-width: 280px; padding: 16px; border-radius: 46px; background: linear-gradient(155deg, #2E3230 0%, #16181A 100%); box-shadow: var(--shadow); }
  .phone-screen { position: relative; border-radius: 30px; overflow: hidden; background: var(--jade); line-height: 0; }
  .phone-screen img { display: block; width: 100%; height: auto; }
  .phone-island { position: absolute; top: 10px; left: 50%; transform: translateX(-50%); width: 32%; height: 22px; background: #16181A; border-radius: 12px; z-index: 2; }

  section.band { padding: 52px 24px; }
  section.band.tint { background: var(--surface-2); border-top: 1px solid var(--border); border-bottom: 1px solid var(--border); }
  .band-inner { max-width: 1080px; margin: 0 auto; }
  .band h2.section-title { font-size: clamp(23px, 3vw, 30px); color: var(--ink); margin: 0 0 8px; text-wrap: balance; }
  .band .section-sub { color: var(--ink-soft); font-size: 15.5px; max-width: 56ch; margin-bottom: 34px; }

  .band-narrow { max-width: 640px; }
  .trust-card { background: var(--surface); border: 1px solid var(--border); border-radius: 18px; padding: 24px; }
  .trust-card .section-sub { margin-bottom: 0; }

  /* How-it-works: a connected track, all four steps visible at once — a
     through-line drawn behind the numbered nodes, horizontal on wide
     screens and collapsing to a vertical line on narrow ones. */
  .track { position: relative; display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 28px; margin-top: 8px; }
  .track-line { position: absolute; top: 19px; left: calc(12.5% - 1px); right: calc(12.5% - 1px); height: 2px; background: var(--border); z-index: 0; }
  .track-step { position: relative; z-index: 1; display: flex; flex-direction: column; gap: 10px; }
  .track-node { flex: none; width: 38px; height: 38px; border-radius: 50%; background: var(--jade); color: var(--bg); display: grid; place-items: center; font-family: var(--font-display); font-weight: 800; font-size: 15px; }
  .track-text h3 { margin: 0 0 4px; font-size: 16.5px; }
  .track-text p { margin: 0; font-size: 14px; color: var(--ink-soft); }
  @media (max-width: 760px) {
    .track { display: flex; flex-direction: column; gap: 24px; padding-left: 19px; }
    .track-line { top: 0; bottom: 0; left: 19px; right: auto; width: 2px; height: auto; }
    .track-step { flex-direction: row; align-items: flex-start; gap: 16px; margin-left: -19px; }
  }
  .learn-more-link { display: inline-block; font-family: var(--font-display); font-weight: 700; font-size: 14px; color: var(--jade); text-decoration: none; }
  .learn-more-link:hover { text-decoration: underline; }

  .feature-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 18px; }
  @media (max-width: 860px) { .feature-grid { grid-template-columns: 1fr 1fr; } }
  @media (max-width: 560px) { .feature-grid { grid-template-columns: 1fr; } }
  .about-feature-grid { grid-template-columns: repeat(3, minmax(0, 1fr)); }
  @media (max-width: 860px) { .about-feature-grid { grid-template-columns: 1fr 1fr; } }
  @media (max-width: 560px) { .about-feature-grid { grid-template-columns: 1fr; } }
  .feature { min-width: 0; background: var(--surface); border: 1px solid var(--border); border-radius: 16px; padding: 22px 20px; display: flex; flex-direction: column; gap: 8px; }
  .feature .glyph { width: 36px; height: 36px; border-radius: 11px; display: grid; place-items: center; background: var(--jade-tint); }
  .feature .glyph svg { width: 18px; height: 18px; }
  .feature h3 { margin: 4px 0 0; font-size: 15.5px; }
  .feature p { font-size: 13.5px; color: var(--ink-soft); margin: 0; }

  .cta-card { background: linear-gradient(155deg, var(--jade) 0%, var(--jade-dark) 100%); color: var(--bg); border-radius: 26px; padding: 44px 40px; display: grid; grid-template-columns: 1.2fr 1fr; gap: 28px; align-items: center; box-shadow: var(--shadow); }
  /* Below 760px the card drops to one column and the icon (.cta-side)
     centers itself within that full-width column — but the heading,
     paragraph and badges above it stayed left-aligned by default, which
     read as "the icons aren't centered" against the centered icon below
     them. Centering the whole column keeps it one consistent block. */
  @media (max-width: 760px) { .cta-card { grid-template-columns: 1fr; padding: 32px 24px; text-align: center; } .cta-card .badges { justify-content: center; } }
  .cta-card h2 { color: var(--bg); margin: 0 0 8px; }
  .cta-card p { color: color-mix(in srgb, var(--bg) 82%, transparent); margin: 0 0 20px; font-size: 15.5px; }
  .cta-card .badges .badge { background: rgba(255,255,255,0.08); border-color: rgba(255,255,255,0.35); color: var(--bg); }
  .cta-card .badges .badge span.small { color: color-mix(in srgb, var(--bg) 70%, transparent); }
  .cta-card .badges .badge:hover { border-color: var(--bg); }
  .cta-side { display: flex; align-items: center; justify-content: center; }
  .cta-mark { width: 120px; height: 120px; border-radius: 22.37%; box-shadow: 0 24px 60px -20px rgba(0,0,0,0.45); }

  .contact-row { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 16px; background: var(--surface); border: 1px solid var(--border); border-radius: 16px; padding: 22px 26px; }
  .contact-row a.email { font-family: var(--font-display); font-weight: 700; font-size: 16px; color: var(--jade); text-decoration: none; overflow-wrap: anywhere; }

  /* About page — reuses the homepage's hero/band/feature-grid language
     rather than the doc-frame template, since it's a story page, not a
     reference document. */
  .mark-lg { width: 44px; height: 44px; border-radius: 22.37%; display: block; }
  .about-hero-band .hero-sub { margin-bottom: 14px; }
  .fact-card { background: var(--surface); border: 1px solid var(--border); border-radius: 20px; padding: 28px; }
  .fact-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 14px; }
  .fact-list li { display: flex; justify-content: space-between; align-items: baseline; gap: 12px; border-top: 1px solid var(--border); padding-top: 12px; }
  .fact-list li:first-child { border-top: none; padding-top: 0; }
  .fact-list span { font-family: var(--font-display); font-size: 12.5px; color: var(--ink-mute); }
  .fact-list strong { font-family: var(--font-display); font-size: 14px; text-align: right; }
  .contact-grid { display: flex; flex-direction: column; gap: 14px; }

  /* Small phones need slimmer page gutters than tablets; this keeps full
     text blocks and navigation visible without shrinking the type into
     something unreadable. */
  @media (max-width: 480px) {
    .top-inner { padding: 12px 16px; }
    .hero { padding: 36px 16px 28px; }
    section.band { padding: 40px 16px; }
    .doc-frame { padding: 36px 16px 52px; }
    .cta-card { padding: 28px 20px; border-radius: 20px; }
    .contact-row { padding: 20px; }
  }

  /* Entrance motion never starts from opacity:0 — content must be visible at
     rest (a static render, a slow first paint, a crawler all see it either
     way); the animation is a bonus transform-only rise for real browsers. */
  @media (prefers-reduced-motion: no-preference) {
    .reveal { animation: rise .5s ease-out both; }
    .reveal.d1 { animation-delay: .08s; }
    @keyframes rise { from { transform: translateY(12px); } to { transform: none; } }
    .feature, .step { transition: transform .2s ease; }
    .feature:hover { transform: translateY(-3px); }
  }
"""

FONT_LINK = '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@500;600;700;800&family=IBM+Plex+Sans:wght@400;500;600&family=Manrope:wght@600;700;800&display=swap">'


def nav(current):
    def link(href, label, key=None):
        cur = ' aria-current="page"' if key == current else ""
        return f'<a href="{href}"{cur}>{label}</a>'
    return f"""<header class="top">
    <div class="top-inner">
      <a class="brand" href="/">
        <img class="mark" src="{ICON}" alt="">
        <span class="wordmark">Table for More</span>
      </a>
      <nav class="crosslinks" aria-label="Main">
        {link('/about', 'About', 'about')}
        {link('/support', 'Support', 'support')}
        <a href="https://www.instagram.com/tableformoreapp/" class="nav-cta" target="_blank" rel="noopener noreferrer">Follow us</a>
      </nav>
    </div>
  </header>"""


FOOTER = """<footer class="site">
    <div class="footer-inner">
      <span>&copy; 2026 Lily Jiang</span>
      <span>Made for food lovers everywhere</span>
      <nav aria-label="Legal">
        <a href="/about">About</a>
        <a href="/privacy">Privacy</a>
        <a href="/terms">Terms</a>
        <a href="/support">Support</a>
        <a href="https://www.instagram.com/tableformoreapp/" target="_blank" rel="noopener noreferrer">Instagram</a>
        <a href="mailto:support@tableformoreapp.com">Contact</a>
      </nav>
    </div>
  </footer>"""


def seo_head(title, description, path, image=OG_IMAGE):
    url = f"{SITE_URL}{path}"
    # Both of these were missing entirely — real bug, not a styling nit. With
    # no viewport tag, mobile browsers render the page at a fake ~980px
    # desktop width and zoom the whole thing down to fit the screen, which is
    # what "doesn't render well on phone, everything looks weird" actually
    # was. charset is declared explicitly too, rather than relying solely on
    # the server's Content-Type header — correct per the HTML5 spec, and the
    # only way emoji/special characters render right for any consumer that
    # doesn't see that header (a saved copy, some in-app browsers, preview
    # tools).
    return f"""<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="canonical" href="{url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Table for More">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{image}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{description}">
<meta name="twitter:image" content="{image}">
<link rel="icon" href="/favicon.png" type="image/png">
<link rel="apple-touch-icon" href="{ICON}">
{FONT_LINK}
<style>{CSS}</style>"""


def slugify(text):
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"&[a-z]+;", "", text)
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def build_toc(body_html):
    """Auto-extracts every <h2> as a TOC entry and stamps matching ids onto
    them — one source of truth, so the rail can never drift from the page."""
    headings = re.findall(r"<h2>(.*?)</h2>", body_html)
    items = []
    for h in headings:
        slug = slugify(h)
        body_html = body_html.replace(f"<h2>{h}</h2>", f'<h2 id="{slug}">{h}</h2>', 1)
        items.append(f'<li><a href="#{slug}">{h}</a></li>')
    return body_html, "".join(items)


def doc_page(title_tag, description, path, eyebrow, h1, meta_html, body_html, current, jsonld="", rail=None):
    if rail is None:
        body_html, toc_items = build_toc(body_html)
        rail = f"""<div class="rail-card"><p class="rail-title">On this page</p><ul class="toc">{toc_items}</ul></div>
    <div class="rail-card"><p class="rail-title">Questions?</p><p>We read every message.</p><a class="email" href="mailto:support@tableformoreapp.com">support@tableformoreapp.com</a></div>"""
    return f"""{seo_head(title_tag, description, path)}
{jsonld}
{nav(current)}
<div class="doc-frame">
  <main>
    <p class="eyebrow">{eyebrow}</p>
    <h1>{h1}</h1>
    <div class="meta">{meta_html}</div>
    {body_html}
  </main>
  <aside class="doc-rail">{rail}</aside>
</div>
{FOOTER}
"""


# ============================== HERO ART (phone mockup) ==============================

def hero_phone():
    """After many rounds of an invented abstract icon (all rejected), the
    direct fix is to stop inventing a symbol and show the actual product.
    The Welcome screen (tried first) was just branding — no real content,
    so it didn't read as "the app" any better than an icon did. The Food
    Passport grid replaces it: real, relevant symbols (a cuisine emoji or
    flag per card — Korean, Japanese, Italian, Ethiopian, Georgian...)
    that are actual app content, not decoration invented for this page."""
    return """<div class="phone-frame">
      <div class="phone-island" aria-hidden="true"></div>
      <div class="phone-screen">
        <img src="/hero-app.png" alt="The Table for More app's Food Passport screen, showing a grid of cuisines to try, each marked with its flag or a food emoji">
      </div>
    </div>"""


def glyph(path):
    return f'<div class="glyph"><svg viewBox="0 0 24 24" fill="none" stroke="var(--jade)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{path}</svg></div>'


# ============================== HOMEPAGE ==============================
HOME_DESC = "Find real restaurants and share the table with new people. Coming soon on iOS and Android."

hero = f"""
<section class="hero">
  <div class="reveal">
    <p class="eyebrow">Coming soon on iOS &amp; Android</p>
    <div class="hero-emoji">🍜 🍣 🌮 🍛</div>
    <h1 class="hero-tagline">There&rsquo;s always a table for one more.</h1>
    <p class="hero-sub">Join a small group at a real restaurant, or host your own.</p>
    <p class="hero-note">A Table is your place in the group&mdash;not a restaurant reservation.</p>
    <div class="badges">
      <a class="badge" href="#download"><span class="small">Coming soon</span><span class="big">📱 App Store</span></a>
      <a class="badge" href="#download"><span class="small">Coming soon</span><span class="big">▶ Google Play</span></a>
    </div>
    <p class="soon-note">Currently in review.</p>
  </div>
  <div class="hero-art reveal d1">{hero_phone()}</div>
</section>
"""

# Accordion, not a static grid — reuses the exact same collapsed-by-default
# <details>/<summary> component as Support's FAQ (asked for directly: "I
# A connected track, not an accordion — "how it works" is a sequence, and
# hiding steps behind a click (right for the FAQ's independent questions)
# works against seeing the flow of one. Every step stays visible at once,
# linked by a through-line, each still just one short caption.
def track_step(num, title, detail):
    return f'<div class="track-step"><div class="track-node"><span>{num}</span></div><div class="track-text"><h3>{title}</h3><p>{detail}</p></div></div>'

how_it_works = f"""
<section class="band" id="how-it-works">
  <div class="band-inner">
    <p class="eyebrow">How it works</p>
    <h2 class="section-title">Four steps, no swiping</h2>
    <div class="track">
      <div class="track-line"></div>
      {track_step("1", "Discover", "Real restaurants nearby, or search any city.")}
      {track_step("2", "Join or host", "Pick a seat, or set the time and group size.")}
      {track_step("3", "Break the ice", "A group chat with conversation starters.")}
      {track_step("4", "Build your passport", "Every Table adds to your food story.")}
    </div>
  </div>
</section>
"""

learn_more = """
<section class="band tint">
  <div class="band-inner band-narrow" style="display:flex; flex-direction:column; align-items:center; text-align:center;">
    <p class="eyebrow">Built for real connection</p>
    <h2 class="section-title">Nothing here is fake</h2>
    <p class="section-sub" style="margin: 0 auto 20px; text-align:center;">Real restaurants, reputation you earn, and a private Food Passport for every table you share.</p>
    <a href="/about" class="learn-more-link">Read more about us &rarr;</a>
  </div>
</section>
"""

trust = """
<section class="band">
  <div class="band-inner band-narrow">
    <div class="trust-card">
      <p class="eyebrow">Built for better meetups</p>
      <h2 class="section-title">Real plans, more peace of mind</h2>
      <p class="section-sub">Every Table is connected to a real restaurant. Keep your profile on your terms, and use in-app reporting if something doesn&rsquo;t feel right.</p>
    </div>
  </div>
</section>
"""

download = f"""
<section class="band" id="download">
  <div class="band-inner">
    <div class="cta-card">
      <div>
        <h2>Get a seat at the table</h2>
        <p>Finishing up App Store and Google Play review. Check back soon.</p>
        <div class="badges">
          <a class="badge" href="#"><span class="small">Coming soon</span><span class="big">📱 App Store</span></a>
          <a class="badge" href="#"><span class="small">Coming soon</span><span class="big">▶ Google Play</span></a>
        </div>
      </div>
      <div class="cta-side"><img class="cta-mark" src="{ICON}" alt="Table for More app icon"></div>
    </div>
  </div>
</section>
"""

contact = """
<section class="band">
  <div class="band-inner">
    <div class="contact-row">
      <div><p style="margin:0 0 2px; font-family: var(--font-display); font-weight:700; font-size:16px;">Questions before you download?</p><p style="margin:0; color: var(--ink-soft); font-size:14px;">We read every message.</p></div>
      <a class="email" href="mailto:support@tableformoreapp.com">support@tableformoreapp.com</a>
    </div>
  </div>
</section>
"""

homepage_jsonld = f"""<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Table for More",
  "url": "{SITE_URL}",
  "logo": "{SITE_URL}{ICON}",
  "email": "support@tableformoreapp.com",
  "founder": {{"@type": "Person", "name": "Lily Jiang"}},
  "areaServed": "Worldwide"
}}
</script>
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "MobileApplication",
  "name": "Table for More",
  "description": "{HOME_DESC}",
  "applicationCategory": "SocialNetworkingApplication",
  "operatingSystem": "iOS, Android",
  "author": {{"@type": "Person", "name": "Lily Jiang"}}
}}
</script>"""

homepage = f"""{seo_head("Table for More", HOME_DESC, "/")}
{homepage_jsonld}
{nav("home")}
{hero}{how_it_works}{learn_more}{trust}{download}{contact}{FOOTER}
"""
Path("index.html").write_text(homepage)

# ============================== ABOUT ==============================
# Deliberately NOT doc_page()'s two-column reference-document frame — About
# is a story/mission page, not something anyone looks something up in, so it
# reuses the homepage's own wide bands and cards instead of a centered
# sidebar layout, and stays visually part of the same flow as "/".
about_hero = f"""
<section class="hero about-hero-band">
  <div class="reveal">
    <p class="eyebrow">About</p>
    <h1>Why Table for More</h1>
    <p class="hero-sub">Eating out is better with company. We help you find it as easily as you find the restaurant.</p>
    <p style="max-width:46ch; color:var(--ink-soft); font-size:15.5px;">Most food apps stop at the restaurant. We add the part that actually makes a meal memorable: who's at the table. Join a small group already headed somewhere, or start your own. Real people, a real restaurant, no swiping first.</p>
  </div>
  <div class="reveal d1">
    <div class="fact-card">
      <img class="mark-lg" src="{ICON}" alt="" style="margin-bottom:16px;">
      <ul class="fact-list">
        <li><span>Category</span><strong>Social dining</strong></li>
        <li><span>Coverage</span><strong>Any city, worldwide</strong></li>
        <li><span>Status</span><strong>Coming soon</strong></li>
      </ul>
    </div>
  </div>
</section>
"""

about_features = f"""
<section class="band tint">
  <div class="band-inner">
    <p class="eyebrow">What makes it different</p>
    <h2 class="section-title">Nothing here is fake</h2>
    <div class="feature-grid about-feature-grid">
      <div class="feature">{glyph('<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M8 3v18M3 9h5"/>')}<h3>Real restaurants, always</h3><p>Actual menus, real hours, and a real reservation link. Never invented.</p></div>
      <div class="feature">{glyph('<path d="M12 2l2.9 6.3 6.9.9-5 4.8 1.2 6.9-6-3.3-6 3.3 1.2-6.9-5-4.8 6.9-.9z"/>')}<h3>Reputation you earn</h3><p>Ratings come only from people who actually finished a Table with you.</p></div>
      <div class="feature">{glyph('<path d="M12 21s-7-4.5-9.5-9A5.5 5.5 0 0 1 12 6a5.5 5.5 0 0 1 9.5 6c-2.5 4.5-9.5 9-9.5 9z"/>')}<h3>A private Food Passport</h3><p>An honest record of the meals and people that made up your year.</p></div>
    </div>
  </div>
</section>
"""

about_story = """
<section class="band">
  <div class="band-inner">
    <p class="eyebrow">Why we built it</p>
    <h2 class="section-title" style="max-width:32ch;">Finding a restaurant is easy. Finding people is not.</h2>
    <p class="section-sub" style="margin-bottom:0;">That gap is the whole reason Table for More exists. Real restaurants, real people, and a Food Passport that grows every time you actually share a meal. Still early, still growing, and shaped directly by the people using it.</p>
  </div>
</section>
"""

about_contact = """
<section class="band tint">
  <div class="band-inner contact-grid">
    <div class="contact-row">
      <div><p style="margin:0 0 2px; font-family: var(--font-display); font-weight:700; font-size:16px;">Questions, ideas, or just want to say hi?</p><p style="margin:0; color: var(--ink-soft); font-size:14px;">We read every message.</p></div>
      <a class="email" href="mailto:support@tableformoreapp.com">support@tableformoreapp.com</a>
    </div>
    <div class="contact-row">
      <div><p style="margin:0 0 2px; font-family: var(--font-display); font-weight:700; font-size:16px;">Partnerships, press, or working together?</p><p style="margin:0; color: var(--ink-soft); font-size:14px;">We'd love to hear from you.</p></div>
      <a class="email" href="mailto:inquiries@tableformoreapp.com">inquiries@tableformoreapp.com</a>
    </div>
  </div>
</section>
"""

about_desc = "Why Table for More exists, what makes it different, and who's building it."
about_page = f"""{seo_head("About | Table for More", about_desc, "/about")}
{nav("about")}
{about_hero}{about_features}{about_story}{about_contact}{FOOTER}
"""
Path("about.html").write_text(about_page)

# ============================== PRIVACY POLICY ==============================
privacy_meta = '<span><strong>Effective</strong> September 17, 2026</span><span><strong>Applies to</strong> the Table for More app and website</span>'
privacy_body = """
<p class="lede">Table for More is built around meeting real people over a real meal, so this page explains plainly what we collect and what we do with it.</p>

<h2>Who we are</h2>
<p>Table for More is operated by Lily Jiang, an individual based in Toronto, Ontario, Canada. This policy applies to the Table for More mobile app and any associated website.</p>

<h2>Information we collect</h2>
<p>You can look around the app (restaurants, cuisines, real menus) as a guest, without an account and without us collecting anything about you. Creating an account and using the social features of the app requires the following:</p>

<div class="tablewrap"><table>
<tr><th>Category</th><th>What it includes</th></tr>
<tr><td>Account info</td><td>Email address, phone number, birthday, full legal name, and a chosen username</td></tr>
<tr><td>Profile</td><td>A profile photo, an optional bio, your favorite cuisines, and &ldquo;food personality&rdquo; tags you choose</td></tr>
<tr><td>Content you create</td><td>Food photos you post, messages you send in a Table's group chat, restaurant reviews, and feedback about tablemates</td></tr>
<tr><td>Activity</td><td>Restaurants you've visited, Tables you've hosted or joined, and check-in times. This builds your private Food Passport</td></tr>
<tr><td>Location</td><td>Your device's approximate location, only while the app is open and only if you grant permission, used to find nearby restaurants</td></tr>
<tr><td>Safety reports</td><td>Reports you submit about a message, person, photo, or Table, including any details you write</td></tr>
</table></div>

<p>We do not collect health data, payment/financial information, or precise background location. We do not use advertising trackers, and Table for More does not request App Tracking Transparency permission because we don't track you across other companies' apps or websites.</p>

<h2>How we use your information</h2>
<ul>
<li>To operate the core features of the app: finding restaurants, creating and joining Tables, group chat, reviews, and your Food Passport</li>
<li>To keep the community safe by screening messages, photos, and feedback for policy violations, and acting on reports</li>
<li>To generate AI conversation starters for a Table's chat, based on the cuisines and interests of the real people attending</li>
<li>To send you account-related email (confirming your address, password resets) and local reminders on your own device (a check-in nudge after a Table starts). We do not send marketing email</li>
<li>To prevent abuse, such as one person creating many accounts or spamming Tables</li>
</ul>

<h2>Your public profile</h2>
<p>Your name, username, avatar, favorite cuisines, food personality tags, and reputation score (built only from people who genuinely shared a finished Table with you) are visible to other signed-in members. Your email, phone number, birthday, and private dining history are never shown to other members.</p>

<h2>Third-party services we use</h2>
<p>We rely on a small number of specialized providers to run the app. None of them are permitted to use your information for their own advertising.</p>

<div class="tablewrap"><table>
<tr><th>Service</th><th>What it's used for</th><th>What it may receive</th></tr>
<tr><td>Supabase</td><td>Our database, authentication, and file storage. Effectively all app data lives here</td><td>All account and content data described above</td></tr>
<tr><td>Anthropic (Claude)</td><td>Generates Table icebreakers, screens chat messages, feedback, and food photos for content that violates our guidelines, and writes restaurant descriptions from public restaurant websites</td><td>Message text, photo images, and restaurant preference data being screened or used to generate a response. Never your email, phone, or full account details</td></tr>
<tr><td>Google Places</td><td>A fallback source for restaurant details (cuisine, photos, hours) when free sources don't have them</td><td>Restaurant search coordinates, not your personal account data</td></tr>
<tr><td>OpenStreetMap</td><td>The primary source of real-world restaurant listings</td><td>Restaurant search coordinates</td></tr>
<tr><td>Unsplash</td><td>Stock photography for restaurants that don't have their own photo</td><td>No personal data</td></tr>
<tr><td>Brevo</td><td>Delivers account emails (confirmation codes, password resets)</td><td>Your email address, for the message being sent</td></tr>
<tr><td>hCaptcha</td><td>Distinguishes real people from automated bots during sign-up and login</td><td>Device and browser signals, per hCaptcha's own privacy policy</td></tr>
</table></div>

<h2>Data storage &amp; security</h2>
<p>Your data is encrypted in transit and at rest. On your device, your session is stored in your phone's secure hardware keystore (Apple's Keychain or Android's Keystore), not in plain, unencrypted storage. Database access is restricted row-by-row so that, for example, one member can never read another member's email, phone number, or birthday.</p>

<h2>Your rights &amp; choices</h2>
<ul>
<li><strong>Access and correction</strong>: view and edit your profile at any time from Settings.</li>
<li><strong>Location and notifications</strong>: both are optional and can be turned off in your device settings; the app works without them, with reduced convenience.</li>
<li><strong>Deletion</strong>: delete your account and personal data from Settings at any time. This is not a blanket erasure of everything tied to your activity: if you hosted a Table, it stays visible to the other real people who attended (their own Food Passport and reviews depend on it), but it's no longer linked to your identity.</li>
</ul>

<h2>Children's privacy</h2>
<p>Table for More is meant for adults meeting other adults in person and is not directed at anyone under 18. We do not knowingly collect information from anyone under 18.</p>

<h2>International users</h2>
<p>Table for More is operated from Canada. If you use the app from another country, your information is transferred to and processed in Canada and in the countries where our service providers above operate.</p>

<h2>Changes to this policy</h2>
<p>If we make a material change to this policy, we'll update the effective date above and, where required by law, notify you directly.</p>

<h2>Contact us</h2>
<p>Questions about this policy or your data can be sent to <a href="mailto:support@tableformoreapp.com">support@tableformoreapp.com</a>.</p>
"""

# ============================== TERMS OF SERVICE ==============================
terms_meta = '<span><strong>Effective</strong> September 17, 2026</span><span><strong>Governing law</strong> Ontario, Canada</span>'
terms_body = """
<p class="lede">Please read these Terms carefully. They cover a service built around meeting real strangers for a real meal, so a few sections matter more than the usual boilerplate.</p>

<h2>1. Acceptance of terms</h2>
<p>By creating an account or using Table for More (&ldquo;the app,&rdquo; &ldquo;the service&rdquo;), you agree to these Terms of Service. If you don't agree, please don't use the app. The app is operated by Lily Jiang (&ldquo;we,&rdquo; &ldquo;us&rdquo;).</p>

<h2>2. Eligibility</h2>
<p>You must be at least 18 years old to create an account. By registering, you confirm that you're 18 or older and that the information you provide, including your name and date of birth, is accurate.</p>

<h2>3. Description of service</h2>
<p>Table for More helps you discover restaurants and organize or join small-group meetups (&ldquo;Tables&rdquo;) with other members. You can also browse the app without an account as a guest, with reduced functionality.</p>

<h2>4. Your account</h2>
<p>You're responsible for keeping your login credentials secure and for all activity under your account. Tell us right away at <a href="mailto:support@tableformoreapp.com">support@tableformoreapp.com</a> if you believe your account has been compromised.</p>

<h2>5. Community guidelines</h2>
<p>Table for More only works if people treat each other well. You agree not to:</p>
<ul>
<li>Harass, threaten, or discriminate against another member</li>
<li>Post content that is illegal, sexually explicit, or promotes violence</li>
<li>Impersonate another person or create a fake or duplicate account</li>
<li>Use the app to solicit, sell, or advertise outside its intended purpose</li>
<li>Attempt to circumvent our safety, moderation, or rate-limiting systems</li>
</ul>
<p>We may remove content, suspend, or terminate accounts that violate these guidelines, with or without notice, at our discretion.</p>

<h2>6. Content you post</h2>
<p>You keep ownership of the photos, messages, and reviews you post. By posting them, you give us a license to store, display, and process that content as needed to operate the app. For example, we might show your food photo to other members, or screen a message for policy violations. Messages, photos, and feedback may be automatically or manually reviewed for content that violates these Terms.</p>

<div class="callout warn">
<p><strong>Tables are not restaurant reservations.</strong> Joining or hosting a Table books your spot in the social group only. It does not create, guarantee, or imply any reservation with the restaurant itself. Where we can find one, we link to the restaurant's own real reservation page. Making that reservation, if you want one, is between you and the restaurant.</p>
</div>

<h2>7. Meeting other members</h2>
<div class="callout warn">
<p>Table for More helps you find and meet new people in person. We do not conduct background checks on members, and we cannot guarantee the identity, intentions, or conduct of anyone you meet through the app. You are solely responsible for your own safety when meeting another member. We encourage meeting in the public setting a Table provides, telling someone else where you're going, and using the in-app reporting tools if anything feels wrong.</p>
</div>

<h2>8. Reporting &amp; moderation</h2>
<p>You can report a message, a person, a photo, or a Table at any time from within the app. We review reports and take action we consider appropriate, which may include removing content or suspending an account, at our discretion and without obligation to explain our reasoning to any party involved.</p>

<h2>9. Third-party services &amp; links</h2>
<p>The app may link to restaurants' own websites or reservation systems, and relies on third-party data providers described in our <a href="/privacy">Privacy Policy</a>. We don't control those third parties and aren't responsible for their content, accuracy, or availability.</p>

<h2>10. Disclaimer of warranties</h2>
<p>The app is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranties of any kind, express or implied. We don't guarantee the app will be uninterrupted, error-free, or that any restaurant information (hours, menu, availability) is perfectly current.</p>

<h2>11. Limitation of liability</h2>
<p>To the fullest extent permitted by law, Lily Jiang will not be liable for any indirect, incidental, or consequential damages arising from your use of the app, including anything arising from your interactions with other members or restaurants, whether met through the app or not.</p>

<h2>12. Indemnification</h2>
<p>You agree to indemnify and hold us harmless from any claim or demand arising from your use of the app or your violation of these Terms.</p>

<h2>13. Termination</h2>
<p>You may delete your account at any time from Settings. We may suspend or terminate your access for violating these Terms or our community guidelines.</p>

<h2>14. Changes to these terms</h2>
<p>We may update these Terms from time to time. If we make a material change, we'll update the effective date above.</p>

<h2>15. Governing law</h2>
<p>These Terms are governed by the laws of the Province of Ontario and the laws of Canada applicable therein, without regard to conflict-of-law principles.</p>

<h2>16. Contact us</h2>
<p>Questions about these Terms can be sent to <a href="mailto:support@tableformoreapp.com">support@tableformoreapp.com</a>.</p>
"""

# ============================== SUPPORT / FAQ ==============================
support_meta = '<span><strong>We usually reply within</strong> 1&ndash;2 business days</span>'


def faq(q, a, open_first=False):
    o = " open" if open_first else ""
    return f'<details class="faq-item"{o}><summary>{q}</summary><p>{a}</p></details>'


faq_groups = [
    ("Getting started", [
        ("What is Table for More?", "An app for finding real restaurants near you and sharing the table with a small group of new people. You can join a Table someone else has already started, or host your own."),
        ("Do I need an account?", "No, you can browse restaurants, cuisines, and real menus as a guest. You'll need a free account once you want to actually join or host a Table, chat, or post a food photo."),
        ("How do Tables work?", "Pick a restaurant, then either join an existing Table with an open seat or host your own by choosing the time and group size. Everyone joining gets a group chat before the Table starts."),
        ("Is booking a Table the same as a restaurant reservation?", "No. Joining or hosting a Table only books your spot in the social group. Where we've found one, we link to the restaurant's own real reservation page. Making an actual reservation is between you and the restaurant."),
    ]),
    ("While you're there", [
        ("What if I'm running late or can't make it?", "Mark yourself &ldquo;Running Late&rdquo; from the Table screen so the group knows. It pauses the no-show clock. If you can't make it at all, you can back out before the Table starts."),
        ("How do the AI conversation starters work?", "Once your Table's chat is empty and everyone's about to meet, we generate a few short icebreakers based on the restaurant and the real interests of who's coming. They disappear once anyone actually starts chatting."),
        ("Is my location shared with other members?", "No. Your location is only used, with your permission, to show you nearby restaurants on your own device. It's never shown to other members or attached to your profile."),
    ]),
    ("Trust, safety &amp; your account", [
        ("How is my safety protected?", "You can report a message, a person, a photo, or a Table at any time, not just afterward. Messages, photos, and feedback are automatically screened for content that violates our guidelines, and reports are reviewed by us directly."),
        ("How does reputation work?", "After a Table, you and your tablemates can rate each other. Your public reputation is built only from people who genuinely finished a real Table with you. A stranger can't affect your score without actually having shared a meal with you."),
        ("How do I delete my account and data?", "Go to Settings &rarr; Delete Account. This removes your personal data; if you hosted a Table, it stays visible to the other real people who attended, since their own history depends on it, but it's no longer linked to your identity."),
        ("I found a bug, or have feedback.", "We'd genuinely like to hear it. Email us at the address below with as much detail as you can (what you were doing, what you expected, what happened instead)."),
    ]),
]
support_body = '<p class="lede">Answers to the questions we hear most. Can&rsquo;t find yours? Email us at the bottom of the page.</p>'
support_toc_items = []
for i, (group_title, items) in enumerate(faq_groups):
    slug = slugify(group_title)
    support_toc_items.append(f'<li><a href="#{slug}">{group_title}</a></li>')
    support_body += f'<p class="faq-group-title" id="{slug}">{group_title}</p>'
    support_body += "".join(faq(q, a, open_first=(i == 0 and j == 0)) for j, (q, a) in enumerate(items))
faq_items = [qa for _, items in faq_groups for qa in items]
support_rail = f"""<div class="rail-card"><p class="rail-title">Jump to</p><ul class="toc">{"".join(support_toc_items)}</ul></div>
    <div class="rail-card"><p class="rail-title">Still stuck?</p><p>We read every message.</p><a class="email" href="mailto:support@tableformoreapp.com">support@tableformoreapp.com</a></div>"""

faq_jsonld = f"""<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [
    {",".join(
        '{"@type":"Question","name":' + repr(q.replace("&rsquo;", "'").replace("&rdquo;", '"').replace("&ldquo;", '"').replace("&amp;", "&")).replace("'", '"') + ',"acceptedAnswer":{"@type":"Answer","text":' + repr(a.replace("&rsquo;", "'").replace("&rdquo;", '"').replace("&ldquo;", '"').replace("&amp;", "&").replace("&mdash;", "-")).replace("'", '"') + '}}'
        for q, a in faq_items
    )}
  ]
}}
</script>"""

# ============================== WRITE ==============================
Path("privacy.html").write_text(doc_page(
    "Privacy Policy | Table for More", "How Table for More collects, uses, and protects your data.",
    "/privacy", "Legal", "Privacy Policy", privacy_meta, privacy_body, "privacy"))
Path("terms.html").write_text(doc_page(
    "Terms of Service | Table for More", "The terms governing your use of Table for More.",
    "/terms", "Legal", "Terms of Service", terms_meta, terms_body, "terms"))
Path("support.html").write_text(doc_page(
    "Support | Table for More", "Frequently asked questions and how to reach the Table for More team.",
    "/support", "Help", "Support &amp; FAQ", support_meta, support_body, "support", jsonld=faq_jsonld, rail=support_rail))

# ============================== robots.txt / sitemap.xml ==============================
Path("robots.txt").write_text(f"User-agent: *\nAllow: /\n\nSitemap: {SITE_URL}/sitemap.xml\n")

pages = ["/", "/about", "/support", "/privacy", "/terms"]
urls = "\n".join(
    f"  <url><loc>{SITE_URL}{p}</loc><lastmod>2026-09-17</lastmod></url>" for p in pages
)
Path("sitemap.xml").write_text(
    f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{urls}\n</urlset>\n'
)

for f in sorted(Path(".").glob("*.html")):
    print(f.name, len(f.read_text()), "bytes")
print("robots.txt, sitemap.xml, icon.png, favicon.png, og-image.png written")
